### ISSUE TITLE
Compatibility with ddev/ddev-redis-7  (password)

### ISSUE THREAD

**Issue by DenisMir** [ddev/ddev-redis-commander#16]
It would be great if this addon would be compatible with `ddev/ddev-redis-7`. This fails at the moment due to `ddev/ddev-redis-7` having the password set to `redis`.

**Comment by julienloizelet** [comment]
Hi @DenisMir,

I've just found that it's possible to define the redis password in a separate docker-compose.yaml file.

For example, if your password is "redis", create a `docker-compose.redis_password.yaml` file with the following content: 

```
services:
    redis-commander:
        environment:
            - REDIS_PASSWORD=redis

```

Then run `ddev start` and it should be ok.

Please let me know if it's working for you.

Thanks
